### ISSUE TITLE
argument error - dogstatsd_vm_stats

### ISSUE THREAD

**Issue by drozzy** [WhoopInc/dogstatsde#31]
I'm getting this weird error when trying to run from Elixir 1.7 and phoenix:

```
[error] GenServer :dogstatsd_vm_stats terminating
** (ArgumentError) argument error
    :erlang.process_info(:undefined, :message_queue_len)
    (dogstatsd) /app/deps/dogstatsd/src/dogstatsd_vm_stats.erl:125: :dogstatsd_vm_stats.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:timeout, #Reference<0.620151675.2178416641.9753>, :"#delay"}
State: {:state, ['erlang.vm', 46], :enabled, [{1, 951300, 951300}, {2, 148000, 974500}, {3, 28400, 17215954100}, {4, 723100, 17215959500}], #Reference<0.620151675.2178416641.9753>, 60000, {7377680, 7371055}, {5735, 25722415, 0}}
```

**Comment by waisbrot** [comment]
Latest release of Elixir is 1.6.6, right? Over at https://github.com/waisbrot/dogstatsde I have updated to test against 1.6.6 and all looks well.

I'm not doing Elixir development, so to improve Elixir support I'd appreciate some help. If you could make something like https://github.com/waisbrot/dogstatsde/tree/master/examples/elixir that produced your error, I could fix it and add it to CI tests.

**Comment by drozzy** [comment]
Sorry, I'm using Datadog's Agent 6 for auto monitoring, so I maybe i'll come back to this in the future.
For now, I'll close it (assume I did something wrong).
